application: smusique-uploader
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /tests/
  static_files: tests/index.html
  upload: tests/

- url: /tests/
  static_dir: tests

- url: /res/
  static_dir: res

- url: /.*
  script: main.py
